site_name: Jupiter Developer Docs
repo_url: https://github.com/jupiter-project
repo_name: jupiter-project
theme:
  name: material
  logo: assets/images/jupiter-logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

